### ISSUE TITLE
How to factor a specific number?

### ISSUE THREAD

**Issue by FalcoGer** [Bdot42/mfakto#29]
I wish to find the factors of a specific number, say `9981288689097387167236403804200527764541749288988075494790957780549135181678131939818850293729529848150563641739687197881364631891780517426633717597900617` from a weak (512bit) RSA public key.

How would I go about doing that with mfakto?

**Comment by Bdot42** [comment]
mfakto is not made to factor artitrary numbers. It can only find small factors of mersenne numbers (2^n-1). It makes use of special properties of such numbers to find any factors of a certain size, but it will not usually completely factor that number. Please refer to the Great Internet Mersenne Prime Search (GIMPS) for details.
