### ISSUE TITLE
Compilation error on Debian

### ISSUE THREAD

**Issue by valeriob01** [Bdot42/mfakto#4]
Downloads/mfakto-master/src$ make
gcc -m64 -Wall -O3 -funroll-loops  -ffast-math -finline-functions -frerun-loop-opt -fgcse-sm -fgcse-las -flto -I/opt/AMDAPP/include -DBUILD_OPENCL -funroll-all-loops -funsafe-loop-optimizations -fira-region=all -fsched-spec-load -fsched-stalled-insns=10 -fsched-stalled-insns-dep=10 -fno-align-labels  -c sieve.c -o sieve.o
sieve.c: In function ‘sieve_free’:
sieve.c:140:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   if (sieve)      free(sieve);      sieve=NULL;
   ^~
sieve.c:140:37: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
   if (sieve)      free(sieve);      sieve=NULL;
                                     ^~~~~
sieve.c:141:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   if (sieve_base) free(sieve_base); sieve_base=NULL;
   ^~
sieve.c:141:37: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
   if (sieve_base) free(sieve_base); sieve_base=NULL;
                                     ^~~~~~~~~~
sieve.c:142:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   if (primes)     free(primes);     primes=NULL;
   ^~
sieve.c:142:37: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
   if (primes)     free(primes);     primes=NULL;
                                     ^~~~~~
sieve.c:143:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   if (k_init)     free(k_init);     k_init=NULL;
   ^~
sieve.c:143:37: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
   if (k_init)     free(k_init);     k_init=NULL;
                                     ^~~~~~
gcc -m64 -Wall -O3 -funroll-loops  -ffast-math -finline-functions -frerun-loop-opt -fgcse-sm -fgcse-las -flto -I/opt/AMDAPP/include -DBUILD_OPENCL -c timer.c -o timer.o
gcc -m64 -Wall -O3 -funroll-loops  -ffast-math -finline-functions -frerun-loop-opt -fgcse-sm -fgcse-las -flto -I/opt/AMDAPP/include -DBUILD_OPENCL -c parse.c -o parse.o
make: *** No rule to make target '/opt/AMDAPP/include/CL/cl.h', needed by 'read_config.o'.  Stop.

**Comment by wedgingt** [comment]
The cl.h file is part of the Nvidia CUDA code/library.  Either you have not installed that or it is not installed at that folder or directory path or something similar.
